### ISSUE TITLE
Error with  example grin-server.toml

### ISSUE THREAD

**Issue by stakervali** [Grinnode-live/grinnode.live#20]
In  [example grin-server.toml](https://github.com/Grinnode-live/grinnode.live/blob/master/grin-server.toml#L210) 

- Seeding type is set to List with line 104 `seeding_type = "List" `

- line 109 is commented which lists seeds list `#seeds = ["mainnet-seed.grinnode.live:3414"]`

When grin server is initialized it gives the error 

```
ERROR grin_util::logger - 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value:
 Configuration("Seeds must be configured for seeding type List")': src/bin\cmd\server.rs:57   0: <unknown>
```

Is the line 109 accidently commented?

**Comment by MCM-Mike** [comment]
`line 109 is commented which lists seeds list #seeds = ["mainnet-seed.grinnode.live:3414"]` 
should be commented-in, so you will get the Seed list from the Grinnode.live `seed-server `

Did you try it with the commented-in version like this:
`seeds = ["mainnet-seed.grinnode.live:3414"]`

**Comment by MCM-Mike** [comment]
Can we close this issue now? @stakervali
